### ISSUE TITLE
Stopped working after properties upgrade

### ISSUE THREAD

**Issue by khaosdoctor** [anpigon/obsidian-book-search-plugin#78]
Hello! The plugin was working before the Obsidian properties upgrade. Now every time I try to add a new book note using the built command "Add new book note" it creates an empty not without any text but the title of the book. It was giving me an error "The file already exists" but it stopped appearing after a while.

If I try "include book metadata" into the current note, nothing happens. Tried to look in the DevTools but there are no errors or alerts whatsoever

**Comment by curtismchale** [comment]
@khaosdoctor I had the same issue. I rebuilt my template with the properties setup and it worked again.

Have you tried rebuilding your template?

**Comment by knowsearchunlock** [comment]
> @khaosdoctor I had the same issue. I rebuilt my template with the properties setup and it worked again.
> 
> Have you tried rebuilding your template?

Hi 

Can you send your new template that's adjusted with the properties in-mind?
Would be great for everyone else as reference

Appreciations!

**Comment by curtismchale** [comment]
@knowsearchunlock here is my template in source mode. So you'll need to paste it into your template that way and then go back to editing mode.

```yaml
---
tags:
  - book
title: "{{title}}"
author: "{{author}}"
total_page: "{{totalPage}}"
publisher: "{{publisher}}"
publish: "{{publishDate}}"
isbn: "{{isbn10}}, {{isbn13}}"
cover: "{{coverUrl}}"
datestarted: 
datefinished: 
readstatus: 
library: 
format: 
genre:
  - "{{category}}"
rating: 
ordered: 
store: 
orderedwhen:
---
```
